### PR TITLE
fix can not generate report when run with --forceExit

### PR DESCRIPTION
**Pull request by joey-he8x**
register self in reporters so that jest will await the promise before exit.
solve the problem that when run with --forceExit, the report will not be generated.

### CODE REVIEW

**Comment by Hargne** [comment]
Hi,
This is an interesting approach to the issue. Thank you.

However this approach introduces a breaking change as it modifies the entire setup of the reporter to use Jest's `reporters` configuration instead of `testResultsProcessor`. Ideally, if we were introduce this additional method of configure Jest, the old configuration should also be available as it is a popular setting.

Another thing to note is that the reporter class is missing a constructor with mandatory arguments.
From the Jest documentation:

> Custom reporter modules must define a class that takes a GlobalConfig and reporter options as constructor arguments

Furthermore, the TravisCI checks have failed on ESLint errors (please have a look at https://github.com/Hargne/jest-html-reporter/wiki/Contributing-Handbook).

Nontheless I believe that this is a valid input which potentially could contribute to further development of this plugin. I will have a look at this and see if I can find a solution that pleases both setups.

Cheers!

**Comment by joey-he8x** [comment]
Good to know that. I forked another fork of your project and found out after i made those changes, so my code was a little messed-up. I will try to fix the issues of eslint.

**Comment by Hargne** [comment]
@joey-he8x , for your information:
I am working on a solution based on this pull request coupled with some code refinements that will allow for you to run the plugin either via `testResultsProcessor` or `reporters`. As soon as I'm done, it would be awesome if you would want to help out testing the code so that it works as expected (since I cannot reproduce the --forceExit issue myself)?

**Comment by joey-he8x** [comment]
u are right about backward compatibility. I just spent some time trying to find a way, but no gain.

**Comment by Hargne** [comment]
@joey-he8x There is now a pull request open #33 where I have implemented this. It would be awesome if you had time to check if it solves the issue.

**Pull request closed without merging**
