### PR TITLE
fix forceExit issue

### PR DESCRIPTION
**Pull request by joey-he8x**
This reason of change is 
`jest/packages/jest-cli/src/reporter_dispatcher.js: 61`
```
async onRunComplete(contexts: Set<Context>, results: AggregatedResult) {
    for (const reporter of this._reporters) {
      reporter.onRunComplete &&
        (await reporter.onRunComplete(contexts, results));
    }
}
```

### CODE REVIEW

**Comment by joey-he8x** [comment]
the fix of test maybe not that fit.

**Comment by Hargne** [comment]
Have you checked that this actually solves tye --forceExit issue?

**Comment by Hargne** [comment]
**First and foremost:** The tests are failing (please run `npm run test` to check that your tests are running as intended and check the TravisCI build check before submitting a PR).

**Secondly,** the introduction of async/ await seems to have exposed original issues with the tests that needs to be resolved:

In src/reportGenerator.js (line 27) needs to convert the xmlBuilder object into a string, like this:
```
content: xmlBuilderOutput.toString(),
```

We need to mock all the config methods at the top of `index.spec.js` like this:
```
const mockedConfigFunctions = {
	setup: jest.fn(),
	getOutputFilepath: () => 'test-report.html',
	getStylesheetFilepath: () => 'style/defaultTheme.css',
	getPageTitle: () => 'Hest',
	getLogo: jest.fn(),
	getDateFormat: jest.fn(),
	getSort: jest.fn(),
	shouldIncludeFailureMessages: () => false,
};
```

Then the test "should return the jest test data if used with Jest reporters configuration" expects the reporter output to be an object, while in fact it returns a Log object.
This needs to be changed into:

```
expect(reporterOutput.logMsg)
	.toEqual('jest-html-reporter >> Report generated (test-report.html)');
```

**Comment by joey-he8x** [comment]
i will fix tests when i have time, hopefully within week

**Comment by joey-he8x** [comment]
@Hargne tests fixed

**Comment by joey-he8x** [comment]
i haven't encounter the issue of xmlBuilderOutput that you mentioned. So I leave it untouched.

**Pull request merged**
