### PR TITLE
Added invocations count in report, configurable

### PR DESCRIPTION
**Pull request by siteriaitaliana**
We have a user case for this as by using jest-circus and retryTimes, we would like to see which test is retried and how many times, to detect flakiness and false positives (test passing because retried and matching in this way not wanted assertions).

### CODE REVIEW

**Comment by siteriaitaliana** [comment]
@Hargne let me know your thoughts about it please

**Comment by Hargne** [comment]
Hi, I will take a look at this as soon as possible! I am away on a break at the moment :)

**Comment by siteriaitaliana** [comment]
@Hargne  any news about this would like to switch away from ur forked version back to this one

**Comment by Hargne** [comment]
@siteriaitaliana I am sorry this took so long to get back to.

I am currently developing v3.0.0 of this plugin, and I wanted to include this feature. However, I cannot seem to replicate any case where invocations becomes anything else but `undefined` (there is very little information about Jest invocations online).

Are you able to share a test case where Jest's invocations actually returns a number?
Thank you.

**Comment by Hargne** [comment]
I will close this PR due to inactivity and that it is outdated by now. Please open again with an answer to the latest question if you still want this to be included.

**Pull request closed without merging**
